# This script tests that the main branch builds correctly
# and passes the test suite.

name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build
